services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
    container_name: portfolio-app
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - portfolio-network

# Nginx removed - configure in 宝塔面板 instead

networks:
  portfolio-network:
    driver: bridge

volumes:
  ssl: